### ISSUE TITLE
请问javaQuarkBBS模块比较多，如何部署呢？

### ISSUE THREAD

**Issue by peterxiemin** [ChinaLHR/JavaQuarkBBS#1]
看各个模块里的pom文件打包都是war，是要部署的tomcat中吗？ 还是说使用maven运行spring-boot：run呢？

**Comment by ChinaLHR** [comment]
直接main方法运行，配置SpringBootServletInitializer，Maven build之后将war包放入Tomcat中运行，或者修改war为jar，build之后直接运行jar包

**Comment by huangdeyao** [comment]
小白求问，怎么导入到本地idea里面呢？

**Comment by ChinaLHR** [comment]
@huangdeyao Clone后直接用idea open打开文件夹即可

**Comment by maatli** [comment]
抱歉，还是不太明白。应该使用Intellij IDEA打开还是使用eclipse，用eclipse导入是多个工程, Intellij IDEA没用过，打开没看到怎么运行和编译，可以给个简单的说明吗

**Comment by MrWenBo** [comment]
感觉没有解决问题呀

**Comment by sunnyblog** [comment]
@peterxiemin @maatli @huangdeyao @MrWenBo [安装文档](https://github.com/sunnyblog/bbs)
