### ISSUE TITLE
部署过程

### ISSUE THREAD

**Issue by 15863004186sunchi** [ChinaLHR/JavaQuarkBBS#13]
本着学习的目的把这个项目clone。下面说一下我的部署过程把。
1 项目的数据库配置是在 quark-common\src\main\resources\application.properties中
2 数据库的建表语句在H:\gitPro\JavaQuarkBBS\resource\sql。数据库sql文件
3 maven编译的时候制定下jdk的版本，还有就是打包方式写成jar。原工程的打包方式是war。编译的时候报错，这是个spring-boot项目，打成jar就可以。
其他的暂时没问题了。我这里访问后台管理页面点解login的时候，网页加载不出来。不知道为什么。管理员的账号和密码分别是lhr和root。

**Comment by BeAShaper** [comment]
你好，我在运行jar包时报错说jar中没有主清单属性，这种情况是为什么呢，感谢感谢

**Comment by 15863004186sunchi** [comment]
你是在那个目录运行jar包的？如果运行admin的话，在quark-admin目录下运行 mvn spring-boot:run就可以起来后台项目。

**Comment by huoher** [comment]
您好，感谢开源。
请问在idea导入的时候，应该选择哪个子项目的``pom.xml``文件

**Comment by ChinaLHR** [comment]
@huoher quark-parent/pom.xml
