### ISSUE TITLE
真的很希望能出一份详细的部署文档，感觉技术架构很前卫，想学习，单苦于无法运行

### ISSUE THREAD

**Issue by pupilask** [ChinaLHR/JavaQuarkBBS#15]
真的很想向大牛们学习一下，感觉技术架构很前卫，想学习，单苦于无法运行，
希望团队能出一份，部署教程，3个war包，1个jar包 分别如何部署

**Comment by ChinaLHR** [comment]
可以参考 [](https://github.com/ChinaLHR/JavaQuarkBBS/issues/1)

**Comment by ChinaLHR** [comment]
可以参考 https://github.com/ChinaLHR/JavaQuarkBBS/issues/1

**Comment by sunnyblog** [comment]
[安装文档](https://github.com/sunnyblog/bbs)

**Comment by sunnyblog** [comment]
@pupilask
