### ISSUE TITLE
觉得项目很不错，然后弄了下，写了份简易的安装文档

### ISSUE THREAD

**Issue by daxiondi** [ChinaLHR/JavaQuarkBBS#18]
[安装文档](https://github.com/sunnyblog/bbs)

**Comment by sunnyblog** [comment]
给想学习却又不动人，大神看了后也可以指导下。

**Comment by ChinaLHR** [comment]
@sunnyblog 看了下install.md，没什么问题

**Comment by wonderfulMorty** [comment]
后台用户密码是多少，好像登录不了

**Comment by maliangnansheng** [comment]
Nan's BBS 南生论坛 基于SSM框架，自适应手机端和电脑端，界面简洁美观，功能完善。分为用户系统和管理系统两部分
地址：https://github.com/maliangnansheng/bbs-ssm
