### ISSUE TITLE
很好奇

### ISSUE THREAD

**Issue by cgnq** [ChinaLHR/JavaQuarkBBS#2]
MyShiroRealm 是通过new出来的，那么调用这个类时候，里面的adminUserService是怎么注入进来的呢

**Comment by ChinaLHR** [comment]
@cgnq  在使用@Configuration注解的配置类中，@Bean注解会告诉Spring这个方法将会返回一个对象， 该对象要注册为Spring应用上下文中的bean。 方法体中包含了最终产生bean实例的逻辑。

By Spring In Action

**Comment by cgnq** [comment]
这样,另外请教一个问题，我用了你的shiro的配置，登录还有登出也是用你的controller，后台UI用的layui，但每第一次登录都会不成功，页面刷新一下，还在登录页面。
![image](https://user-images.githubusercontent.com/807056/34024041-1918afe6-e140-11e7-8802-24d02fbb6f72.png)
login方法是200但是没有跳转

**Comment by ChinaLHR** [comment]
@cgnq 这个应该是登录成功后shiro会去session中找出之前的保存的请求进行跳转，如果没有保存才会跳转到配置的successUrl导致的，有时间我再去修复一下

**Comment by cgnq** [comment]
@ChinaLHR 感谢回复，这个问题我找到了，是前端用ajax异步请求，后端未返回，导致前端js直接返回false造成的，框架非常不错。持续关注
