### ISSUE TITLE
请问该工程该如何打包呢？

### ISSUE THREAD

**Issue by renxuetao** [ChinaLHR/JavaQuarkBBS#20]
新手，请教一下该工程该如何打包部署，求教

**Comment by ChinaLHR** [comment]
#18 

可以参考下这个

**Comment by renxuetao** [comment]
> #18
> 
> 可以参考下这个

不好意思，比较弱鸡，再请假一下，目前这个结构我已经运行起来，并且每个module都可以打出jar，但是如果这种结构想部署到服务器的话，如何打包出一个大的war包呢？

**Comment by ChinaLHR** [comment]
@renxuetao 这里不支持打出一个大的war包的
