### ISSUE TITLE
大佬，小白想学一下，但编译报错啊

### ISSUE THREAD

**Issue by yueying7** [ChinaLHR/JavaQuarkBBS#21]
java: 对于DefaultEventLoopGroup(int,<匿名java.util.concurrent.ThreadFactory>), 找不到合适的构造器
    构造器 io.netty.channel.DefaultEventLoopGroup.DefaultEventLoopGroup(int,java.util.concurrent.Executor)不适用
      (参数不匹配; <匿名java.util.concurrent.ThreadFactory>无法转换为java.util.concurrent.Executor)
    构造器 io.netty.channel.DefaultEventLoopGroup.DefaultEventLoopGroup(int,io.netty.util.concurrent.ExecutorServiceFactory)不适用
      (参数不匹配; <匿名java.util.concurrent.ThreadFactory>无法转换为io.netty.util.concurrent.ExecutorServiceFactory)

**Comment by ChinaLHR** [comment]
修改netty-all到4.x版本试下
