### ISSUE TITLE
SEO如何解决？

### ISSUE THREAD

**Issue by xuanyuan1hao** [ChinaLHR/JavaQuarkBBS#5]
项目分层架构是不错，但是对于互联网的web项目来说SEO就很差了。所有的请求都是json请求，爬虫、蜘蛛对于这种json请求的友好度很差。

**Comment by ChinaLHR** [comment]
多谢指点，前后端分离确实存在seo的问题，在知乎看到一个问题讲解的不错
https://www.zhihu.com/question/52235652

**Comment by ChinaLHR** [comment]
多谢指点，前后端分离确实存在seo的问题，在知乎看到一个问题讲解的不错
https://www.zhihu.com/question/52235652
