### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by lesvere** [ChinaLHR/JavaQuarkBBS#6]
☁  quark-portal [master] ⚡ mvn clean install
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building quark-portal 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ quark-portal ---
[INFO] Deleting /Users/lesvere/Code/Java/JavaQuarkBBS/quark-portal/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ quark-portal ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 162 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ quark-portal ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to /Users/lesvere/Code/Java/JavaQuarkBBS/quark-portal/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] 不再支持源选项 1.5。请使用 1.6 或更高版本。
[ERROR] 不再支持目标选项 1.5。请使用 1.6 或更高版本。
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.868 s
[INFO] Finished at: 2018-02-03T17:59:24+08:00
[INFO] Final Memory: 16M/55M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project quark-portal: Compilation failure: Compilation failure: 
[ERROR] 不再支持源选项 1.5。请使用 1.6 或更高版本。
[ERROR] 不再支持目标选项 1.5。请使用 1.6 或更高版本。
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
☁  quark-portal [master] ⚡

**Comment by ChinaLHR** [comment]
@lesvere 应该是JDK版本不匹配的问题

**Comment by willliuwx** [comment]
用1.8解决

**Comment by lesvere** [comment]
☁  quark-portal [master] ⚡ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)
☁  quark-portal [master] ⚡

**Comment by lesvere** [comment]
macOS High Sierra 10.13.2

☁ quark-portal [master] ⚡ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**Comment by lesvere** [comment]
http://blog.csdn.net/sosous/article/details/78312867

**Comment by lesvere** [comment]
install success!

**Comment by lesvere** [comment]
Results :

Tests in error:
  getUserByApi(com.quark.porent.service.impl.UserServiceImplTest)

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.958 s
[INFO] Finished at: 2018-02-06T02:07:10+08:00
[INFO] Final Memory: 29M/98M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project quark-portal: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/lesvere/Code/Java/JavaQuarkBBS/quark-portal/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by lesvere** [comment]
Results :

Tests in error:
  getUserByApi(com.quark.porent.service.impl.UserServiceImplTest)

Tests run: 2, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.958 s
[INFO] Finished at: 2018-02-06T02:07:10+08:00
[INFO] Final Memory: 29M/98M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project quark-portal: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/lesvere/Code/Java/JavaQuarkBBS/quark-portal/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ChinaLHR** [comment]
@lesvere 换成1.8的试试

**Comment by lesvere** [comment]
ok

**Comment by lesvere** [comment]
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/shared/maven-shared-utils/0.1/maven-shared-utils-0.1.jar (155 kB at 14 kB/s)
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 16 source files to /Users/lesvere/Code/java/study/quark-portal/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/lesvere/Code/java/study/quark-portal/src/main/java/com/quark/porent/utils/HttpClientUtils.java:[83,63] diamond operator is not supported in -source 1.5
  (use -source 7 or higher to enable diamond operator)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:15 min
[INFO] Finished at: 2018-02-13T15:52:44+08:00
[INFO] Final Memory: 20M/192M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project quark-portal: Compilation failure
[ERROR] /Users/lesvere/Code/java/study/quark-portal/src/main/java/com/quark/porent/utils/HttpClientUtils.java:[83,63] diamond operator is not supported in -source 1.5
[ERROR]   (use -source 7 or higher to enable diamond operator)
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
☁  quark-portal [master]
☁  quark-portal [master]
☁  quark-portal [master]
☁  quark-portal [master]
☁  quark-portal [master] java --version
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
☁  quark-portal [master] mvn --version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T15:58:13+08:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre
Default locale: en_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.3", arch: "x86_64", family: "mac"
☁  quark-portal [master]

**Comment by lesvere** [comment]
☁  java  mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.074 s
[INFO] Finished at: 2018-02-13T16:03:32+08:00
[INFO] Final Memory: 6M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Users/lesvere/Code/java). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
☁  java  java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
☁  java  mvn --version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T15:58:13+08:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/jre
Default locale: en_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.3", arch: "x86_64", family: "mac"
☁  java
