### ISSUE TITLE
IDE工具是哪个？

### ISSUE THREAD

**Issue by longyinzaitian** [ChinaLHR/JavaQuarkBBS#9]
请问IDE工具是哪个来构建的项目呢？
我使用Myeclipse和IntelliJ IDE来导入都不行。

**Comment by ChinaLHR** [comment]
@longyinzaitian 使用的是IntelliJ IDE

**Comment by sunnyblog** [comment]
[安装文档](https://github.com/sunnyblog/bbs) @longyinzaitian
